[workspace]
authors = ["cadenpage <ckp634@my.utexas.edu>"]
channels = ["conda-forge"]
name = "rotom"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]
calibration-gui = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; python -m motors.calibration_gui'"
homing-offset = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; python /home/caden/Documents/rotom/src/examples/homing_offset.py'"
home = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; python /home/caden/Documents/rotom/src/examples/home.py'"
export-joint-limits = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; python /home/caden/Documents/rotom/src/examples/export_joint_limits.py'"
ros2-motor-bridge = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; source /opt/ros/humble/setup.bash; source /home/caden/Documents/rotom/src/ros2_ws/install/setup.bash; ros2 run rotom_control rotom_motor_bridge'"
ros2-build = "bash -lc 'source /opt/ros/humble/setup.bash; cd /home/caden/Documents/rotom/src/ros2_ws; colcon build --symlink-install'"
ros2-moveit-real = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; source /opt/ros/humble/setup.bash; source /home/caden/Documents/rotom/src/ros2_ws/install/setup.bash; ros2 launch rotom_moveit_config real_hw.launch.py'"


[dependencies]
python = "3.10.*"
tqdm = ">=4.67.3,<5"
pygame = ">=2.6.1,<3"
pip = ">=26.0.1,<27"
py-opencv = ">=4.5,<5"
numpy = ">=1.24,<2"

[pypi-dependencies]
feetech-servo-sdk = ">=1.0.0, <2"
