[workspace]
authors = ["cadenpage <ckp634@my.utexas.edu>"]
channels = ["conda-forge"]
name = "rotom"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]
calibration-gui = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; python -m motors.calibration_gui'"
homing-offset = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; python /home/caden/Documents/rotom/src/examples/homing_offset.py'"
home = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; python /home/caden/Documents/rotom/src/examples/home.py'"
export-joint-limits = "bash -lc 'export PYTHONPATH=/home/caden/Documents/rotom/src:/home/caden/Documents/rotom/.pixi/envs/default/lib/python3.10/site-packages:$PYTHONPATH; python /home/caden/Documents/rotom/src/examples/export_joint_limits.py'"


[dependencies]
python = "3.10.*"
tqdm = ">=4.67.3,<5"
pygame = ">=2.6.1,<3"
pip = ">=26.0.1,<27"
py-opencv = ">=4.5,<5"
numpy = ">=1.24,<2"

[pypi-dependencies]
feetech-servo-sdk = ">=1.0.0, <2"
